/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ImageImageIdImport } from './routes/image.$imageId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ImageImageIdRoute = ImageImageIdImport.update({
  id: '/image/$imageId',
  path: '/image/$imageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/image/$imageId': {
      id: '/image/$imageId'
      path: '/image/$imageId'
      fullPath: '/image/$imageId'
      preLoaderRoute: typeof ImageImageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image/$imageId': typeof ImageImageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image/$imageId': typeof ImageImageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/image/$imageId': typeof ImageImageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/image/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/image/$imageId'
  id: '__root__' | '/' | '/image/$imageId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageImageIdRoute: typeof ImageImageIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageImageIdRoute: ImageImageIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/image/$imageId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/image/$imageId": {
      "filePath": "image.$imageId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
